### ISSUE TITLE
Use Swagger Documentation tool for the backend

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/nebraska#166]
Currently we dont have any doc for the backend apis and for every api request we have to manually figure out what all responses we can get.
For generating swagger docs we can use 
swaggo/swag 
https://github.com/swaggo/swag

**Comment by abraarsyed** [comment]
Hello, I would like to take up this issue and work on it. 

I have setup the repository locally and running the backend succesfully. I have successfully configured gin-swagger with the repository and here is simple demo of the setup:
![image](https://user-images.githubusercontent.com/6316109/121979369-ac5de800-cda7-11eb-884d-d76d5d3d47de.png)

I have the following doubts:
1. Is this correct? If yes, can I commit the changes and send a PR?

**Comment by abraarsyed** [comment]
I have further improved it by removing the error shown in previous image, i.e., internal server error due to doc.json:
![image](https://user-images.githubusercontent.com/6316109/121980743-268f6c00-cdaa-11eb-858f-b409352ddf55.png)

**Comment by abraarsyed** [comment]
PR sent for following issue: https://github.com/kinvolk/nebraska/pull/397

**Comment by yolossn** [comment]
Hey @abraarsyed, Thanks for coming up with a PR. Looks like comments in [Declarative Comments Format](https://github.com/swaggo/swag#declarative-comments-format) are not added, that is why the swagger file shows `No operations defined in spec`. You can follow the [getting-started](https://github.com/swaggo/swag#getting-started) section of swaggo/swag to add the comments above each handler function.

**Comment by abraarsyed** [comment]
Hey @yolossn, thank you so much for reviewing my PR. I thought that this issue is `good first issue` and it is about integrating the swagger tool so that the developers can start using it and add those declarative comments to their handler functions since they will know better about what each handler function is doing.

So, my doubt is that am I supposed to add the comments to just one handler function as a demo example or to all the handler functions? If it is for one, its easy but it is all the functions, then how do I go about it? Since I am new to the architecture and codebase, what would you suggest? Can you guide me a little on this please.

**Comment by yolossn** [comment]
Hey @abraarsyed, Please add an example comment for others to follow. Maybe, try  [this](https://github.com/kinvolk/nebraska/blob/8bbb105be251177ef04d0af826045fe8dbfa30bf/backend/cmd/nebraska/controller.go#L315) handler function. Feel free to ask questions if you have any.

**Comment by abraarsyed** [comment]
@yolossn Thank you, I am working on it. Will keep you updated

**Comment by abraarsyed** [comment]
Hey @yolossn, thank you for your guidance, I have added the docs for handler function which you had pointed out. Here is the commit details: a5797ae873fedbf374f995d63da9a3afd20546d4

**Comment by yolossn** [comment]
Thank you, I will have a look.

**Comment by abraarsyed** [comment]
Hey @yolossn, I have made all the changes suggested by you. Can you help me with the next steps and also if everything looks good to you then possibly, closing this PR? Thank you :)
