### ISSUE TITLE
Cannot host packages without using syncer

### ISSUE THREAD

**Issue by JesusRo** [kinvolk/nebraska#380]
Hi,

I was trying to setup a nebraska instance which should not download payload updates in advance but host them when a flatcar instance gets the updates and I was not able to.

By the documentation I understood both features are independent one from each other but seems it not the case
Using the example provided on https://github.com/kinvolk/nebraska/blob/ae118395d5e1a0d6a81c9877944bd3e84587ca66/docs/managing-updates.md#flatcar-container-linux-packages-in-nebraska

`nebraska -host-flatcar-packages=true -flatcar-packages-path=/PATH/TO/STORE/PACKAGES -nebraska-url=http://your.Nebraska.host:port`

I did couple of upgrade and no packages were stored at /PATH/TO/STORE/PACKAGES, only when adding `-enable-syncer` they are automatically downloaded to the path

Could you please confirm that host-flatcar-packages requires enable-syncer?

Thanks in advance

**Comment by joaquimrocha** [comment]
Hi @JesusRo ,

The syncer is for synchronizing Flatcar Container Linux packages' info, i.e. when there's an update available and you have channels whose name matches the upstream ones (`alpha`, `beta`, `stable`), it will create the packages with the new FCL version.
This option will not download the payloads though, so it doesn't require storage.

The `-host-flatcar-packages` option is, as you expected, the option for **also** storing the packages. But it is supposed to be used with the syncer, as the goal with it is to download package updates set up by the syncer.

Maybe we should validate that the syncer is enabled when the host option is true, and return an error otherwise.

If you are manually setting up the packages and you expected them to get downloaded directly, that's not possible as in that case, users can also just download the packages externally and set up the packages manually pointing to the downloaded payloads' location.

We are also working on making the sync option a bit more controllable: #305 .

I am closing the issue hoping I answered your question. If I haven't or if you have other use-cases you think would be useful for most users, please reply or open an issue with that concrete feature request. Cheers.

**Comment by JesusRo** [comment]
Hi @joaquimrocha 
Clear to me now, thanks a lot for the info.

Regards
