### ISSUE TITLE
Allow to select time interval for data display

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#72]
By default Nebraska shows the instances' event history for the past 24h. However, users may be interested in changing this time interval to something different, so we should show those options in the UI.

**Comment by t-lo** [comment]
It's somewhat challenging to restore historic data as we only record the last timestamp of an instance's update check, overwriting previous timestamps. From the `instance_application` table alone history cannot be restored - we additionally need information on when an instance first registered. The `instance` table's `created_ts` column is helpful for this.

To get historic data for a given point in time `ts`,
1. get all instances that have been registered before `ts`, then
2. filter all instances that have not checked for updates since `ts - 1 day`.

SQL:
```sql
SELECT count(*) FROM instance_application as ia, instance as i
WHERE i.id = ia.instance_id 
-- Input: the point in time where we want to count instances.
AND i.created_ts < to_timestamp('20200317 15:30:00', 'YYYYMMDD HH24:MI:SS')
-- Input: Same as above.
AND ia.last_check_for_updates > to_timestamp('20200317 15:30:00', 'YYYYMMDD HH24:MI:SS') - interval '1 day';
```

Convenience SQL function to return active instances for a whole date range:
```sql
DO  $$
declare
	q text;
	res record;
	start_ts timestamp := to_timestamp('20190101 15:30:00', 'YYYYMMDD HH24:MI:SS');
	end_ts timestamp := to_timestamp('20200317 15:30:00', 'YYYYMMDD HH24:MI:SS');
	curr_ts timestamp := start_ts;
	incr interval := '1 day';
begin

loop
    q := 'SELECT count(*) FROM instance_application as ia, instance as i'
           ' WHERE i.id = ia.instance_id'
           ' AND i.created_ts < ''' || curr_ts || ''' '
           ' AND ia.last_check_for_updates > ''' || curr_ts - interval '1 day' || ''';';
    execute q into res;
    raise notice '%: %', curr_ts, res;
    curr_ts := curr_ts + incr;
    exit when curr_ts >= end_ts;
end loop;
END; $$
```

**Comment by t-lo** [comment]
I've been poking a related problem - extract historic active instance counts. Dumping my progress here with the hope it will be useful.

It's somewhat challenging to restore historic active instance data as we only record the last timestamp of an instance's update check, overwriting previous timestamps. From the `instance_application` table alone history cannot be restored - we additionally need information on when an instance first registered. The `instance` table's `created_ts` column is helpful for this.

To get historic data for a given point in time `ts`,
1. get all instances that have been registered before `ts`, then
2. filter all instances that have not checked for updates since `ts - 1 day`.

**SQL**
```sql
SELECT count(*) FROM instance_application as ia, instance as i
WHERE i.id = ia.instance_id 
-- Input: the point in time where we want to count instances.
AND i.created_ts < to_timestamp('20200317 15:30:00', 'YYYYMMDD HH24:MI:SS')
-- Input: Same as above.
AND ia.last_check_for_updates > to_timestamp('20200317 15:30:00', 'YYYYMMDD HH24:MI:SS') - interval '1 day';
```

**Comment by joaquimrocha** [comment]
FTR (and discussing on Slack). @t-lo is proposing this SQL, which is very similar to what already exists to retrieve the instances count (hardcoded for the last 24h), for being able to infer what instances were "valid" (pinged Nebraska within a time period or after) for a certain period.

So we can do the modifications to the backend in order to require an optional end timestamp when we adjust the length of the period (i.e. this issue will use the end timestamp of `now()`, but we can use the same API endpoint for getting the instances count over a period of time during a time series). An issue will be opened about this.

**Comment by joaquimrocha** [comment]
Closing this one since it's done (but #161 remains open as it's different).
