### ISSUE TITLE
Second update request unexpectedly returns updateInProgressOnInstance

### ISSUE THREAD

**Issue by iaguis** [kinvolk/nebraska#76]
When sending a first request to the update server the response is the new version as expected. However, subsequent requests show `error-updateInProgressOnInstance` which is not consistent with CoreOS' CoreUpdate.

### How to reproduce

Using this request file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="update_engine-0.4.10" updaterversion="update_engine-0.4.10" installsource="scheduler" ismachine="1">
    <os version="Chateau" platform="CoreOS" sp="2191.0.0_x86_64"></os>
    <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" track="alpha" bootid="{90b0e235-2b50-4a0e-9619-bc014ca2fcfd}" oem="" oemversion="" alephversion="2191.0.0" machineid="592cfdb69c7f4a29a6b361b60cedd954" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
        <ping active="1"></ping>
        <updatecheck></updatecheck>
        <event eventtype="3" eventresult="2" previousversion="0.0.0.0"></event>
    </app>
</request>
</xml>
</details>
```

#### Nebraska behavior

```console
core@flatcar-01 ~ $ curl -s -X POST -d @request.xml https://public.update.flatcar-linux.net/v1/update/ | xmllint --pretty 1 -
<?xml version="1.0"?>
<response protocol="3.0" server="coreroller">
  <daystart elapsed_seconds="0"/>
  <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" status="ok" track="alpha">
    <ping status="ok"/>
    <updatecheck status="ok">
      <urls>
        <url codebase="https://update.release.flatcar-linux.net/amd64-usr/2275.0.0/"/>
      </urls>
      <manifest version="2275.0.0">
        <packages>
          <package hash="Xh+rt5I8pFTDVj1j+eKlt85JsKE=" name="flatcar_production_update.gz" size="466774008" required="true"/>
        </packages>
        <actions>
          <action event="postinstall" ChromeOSVersion="" sha256="mHsavz23FdX0uvlF1NHHcpJz2HU9qY33eoyC1Y6F+2Q=" needsadmin="false" IsDelta="false" DisablePayloadBackoff="true"/>
        </actions>
      </manifest>
    </updatecheck>
    <event status="ok"/>
  </app>
</response>
core@flatcar-01 ~ $ curl -s -X POST -d @request.xml https://public.update.flatcar-linux.net/v1/update/ | xmllint --pretty 1 -
<?xml version="1.0"?>
<response protocol="3.0" server="coreroller">
  <daystart elapsed_seconds="0"/>
  <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="2191.0.0" status="error-updateInProgressOnInstance" track="alpha">
    <ping status="ok"/>
    <event status="ok"/>
  </app>
</response>
```

#### CoreUpdate behavior

```console
core@flatcar-01 ~ $ curl -X POST -d @request.xml https://public.update.core-os.net/v1/update/
<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="ok">
   <urls>
    <url codebase="https://update.release.core-os.net/amd64-usr/2275.0.0/"></url>
   </urls>
   <manifest version="2275.0.0">
    <packages>
     <package name="update.gz" hash="2dePfsufko+c0o/OJOG2VHzf0OA=" hash_sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" size="467681292" required="false"></package>
    </packages>
    <actions>
     <action event="postinstall" sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" DisablePayloadBackoff="true"></action>
    </actions>
   </manifest>
  </updatecheck>
 </app>
</response>
core@flatcar-01 ~ $ curl -X POST -d @request.xml https://public.update.core-os.net/v1/update/
<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="ok">
   <urls>
    <url codebase="https://update.release.core-os.net/amd64-usr/2275.0.0/"></url>
   </urls>
   <manifest version="2275.0.0">
    <packages>
     <package name="update.gz" hash="2dePfsufko+c0o/OJOG2VHzf0OA=" hash_sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" size="467681292" required="false"></package>
    </packages>
    <actions>
     <action event="postinstall" sha256="xLPJ8UYxT4ywyn34JIKe1q23/9/GNDJhMQ8AMe3nBBw=" DisablePayloadBackoff="true"></action>
    </actions>
   </manifest>
  </updatecheck>
 </app>
</response>
```

**Comment by krnowak** [comment]
Some notes:

- when processing the request, events are processed before update checks
- processing events is mostly about triggering some consequences
  - `eventtype="3"` means "update complete"
  - `eventresult="2"` means "success, reboot"
  - normally the consequence of such an event is to set the status of the instance to "update complete"
- processing update checks is about granting an update to an instance after a bunch of checks (versions and stuff)

With a request above, the process should look like for both requests:

- event processing results in instance status being "update complete"
- update check processing results in instance status being "update granted"

But then we have this snippet of code, executed before triggering the event consequences:

https://github.com/kinvolk/nebraska/blob/c97f450e988c2e9357956486c9f5977031337ca4/pkg/api/events.go#L104-L109

The condition meets exactly what is in the request. Why this "temporary hack" is there, I don't know. It's there since the initial commit.

So, right now the process looks like this:

first request
- events processing results in nothing, because of the above snippet
- update check processing results in instance status being "update granted"

second request
- events processing results in nothing, because of the above snippet
- update check processing results in an "update in progress" error, because instance status is not "update complete", but "update granted".

**Comment by joaquimrocha** [comment]
> So, right now the process looks like this:
> 
> first request
> 
> events processing results in nothing, because of the above snippet
> update check processing results in instance status being "update granted"
> second request
> 
> events processing results in nothing, because of the above snippet
> update check processing results in an "update in progress" error, because instance status is not "update complete", but "update granted".

Thanks for looking into this @krnowak .

So AFAIU from what you're saying, the difference with the CoreOS Updater is that Nebraska is assuming that "update in progress" is true from the moment an update is granted.
The obvious way to proceed, just like @iaguis had mentioned on Slack yesterday, seems to be to consider "upgrade in progress" only from the moment that the instance is _downloading/downloaded/rebooting_ instead of the _granted_ state.

We should also test that behavior (i.e. what it replies when the instance is downloading/downloaded./etc.) against CoreUpdater to make sure we're not diverging beyond this state.

**Comment by krnowak** [comment]
The instance is considered to be in "update in progress" when it is either "granted", "downloading", "downloaded" or "installed" (means installed, but not applied, I suppose that for OS update it would mean rebooting), see https://github.com/kinvolk/nebraska/blob/c97f450e988c2e9357956486c9f5977031337ca4/pkg/api/updates.go#L62-L67

We need to be careful with changing it, because granting the update marks the application instance to have an update in progress: https://github.com/kinvolk/nebraska/blob/c97f450e988c2e9357956486c9f5977031337ca4/pkg/api/updates.go#L164

This may affect some statistics: https://github.com/kinvolk/nebraska/blob/c97f450e988c2e9357956486c9f5977031337ca4/pkg/api/groups.go#L202-L233

The update in progress is cleared when when we set the application instance status to "complete". Setting this status happens during triggering the event consequences. This trigger doesn't happen because of the snippet with the "temporary hack" I posted in the earlier comment. Any idea why it is there? It looks to me that the getting rid of it would also fix the issue.

**Comment by joaquimrocha** [comment]
Keep in mind that at the moment (and IIRC) we're not exposing the statistics in the UI.
I think you are right that we should be careful not change any ongoing behavior as much as possible. 

So maybe we can change the response behavior but keep the statiscs unnaffected. My only point (even though it's an obvious one) was that we should still at this point try to mimic the response behavior that CoreOS works as much as possible, so any CoreOS clients can more seamingly move to Flatcar. So even if internally our statistics say that a Granted status means "instance is upgrading", what we reply to the previously mentioned queries doesn't have to return that error IMO.

**Comment by krnowak** [comment]
Statistics are used during the rollout enforcement, so I'd be careful with tinkering with them.

Also, this CoreUpdate stuff, is that a closed source service? 

Anyway, I tried to have some repeatable way of reproducing the issue at hand. So, I've got a branch - https://github.com/kinvolk/nebraska/tree/krnowak/issue-76.

To reproduce the issue with the branch do:
```
git revert HEAD
make backend dbtools
docker build -f Dockerfile.postgres -t nebraska/postgres .
./rundb.sh
# wait until the db is ready
./bin/initdb -with-sample-data
./runcmd.sh
# switch to other terminal tab
./curl.sh
./curl.sh
```

The output should be the OK response followed by the error-updateInProgressOnInstance response. If you skip the "revert" step, then you should get the OK response twice.

**Comment by krnowak** [comment]
I took a step back and read [the omaha client-server protocol v3 documentation](https://github.com/google/omaha/blob/master/doc/ServerProtocolV3.md). First of all - this request is invalid. I suppose that CoreUpdater and Nebraska are just being nice in accepting it. The reason is that the `<app>` element cannot contain both `<event>` and `<updatecheck>` child elements. I can see that CoreUpdater seems to ignore the `<event>` child from request in this case as there is no `<event>` element in the response. There is also no `<ping>` element in response, but I don't know why.

Anyway. I think that once the server grants an update and the client doesn't act on it, but asks again for the update, we can send the information about the update again. I updated the PR #107.
